### ISSUE TITLE
compile error on msys2 with MS Windows7

### ISSUE THREAD

**Issue by nagayasu-shinya** [yuki-kimoto/SPVM-solo#17]
Msys2＆Ｗindows7 で make してみたところ、コンパイルエラーが出ました。
sperl_yacc.h を生成する前にsperl_yacc_util.cをコンパイルするのがダメなようです。

$ make
gcc -MD -MF objs/sperl_switch_info.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_switch_info.o sperl_switch_info.c
gcc -MD -MF objs/sperl_op.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_op.o sperl_op.c
sperl_op.c: In function 'SPerl_OP_resolve_field_name':
sperl_op.c:651:17: warning: unused variable 'parser' [-Wunused-variable]
   SPerl_PARSER* parser = sperl->parser;
                 ^~~~~~
gcc -MD -MF objs/sperl_sub.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_sub.o sperl_sub.c
gcc -MD -MF objs/sperl_vm_stack.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_vm_stack.o sperl_vm_stack.c
gcc -MD -MF objs/sperl_bytecode_builder.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_bytecode_builder.o sperl_bytecode_builder.c
gcc -MD -MF objs/sperl_memory_pool.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_memory_pool.o sperl_memory_pool.c
gcc -MD -MF objs/sperl_constant_pool.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_constant_pool.o sperl_constant_pool.c
gcc -MD -MF objs/sperl_vm.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_vm.o sperl_vm.c
gcc -MD -MF objs/sperl_yacc_util.Po -std=c99 -g -O -Wall -Wextra -c -o objs/sperl_yacc_util.o sperl_yacc_util.c
sperl_yacc_util.c:10:24: fatal error: sperl_yacc.h: No such file or directory
 #include "sperl_yacc.h"
                        ^
compilation terminated.
make: *** [Makefile:15: objs/sperl_yacc_util.o] Error 1

**Comment by nagayasu-shinya** [comment]
Makefile  内の依存関係の指定を修正すればビルドできました。
下記の2行

(OBJDIR)/sperl_toke.o: sperl_toke.c sperl_yacc.h
$(OBJDIR)/sperl_yacc.o: sperl_yacc.c sperl_yacc.h

を

$(libsperl_OBJS) : $(generated_sources)

としたほうが楽かもしれません。

**Comment by nagayasu-shinya** [comment]
make -j のように並列ビルドも視野に入れるなら、Ｍakefile内で明示的に依存関係を描いてあげるほうが固いかなと思います。

**Comment by akinomyoga** [comment]
ごめんなさい。これは私のミスです。以前 `sperl_yacc.c` だったものを `sperl_yacc_util.c` に改名して、`sperl_yacc.tab.c` を ~~`sperl_yacc.tab.h`~~ `sperl_yacc.c` (**編集**) に改名したときに依存関係を更新するのが抜けていたみたいです。

**Comment by akinomyoga** [comment]
#18 に PR 出しました。

**Comment by yuki-kimoto** [comment]
@nagayasu-shinya Windows7でのバグ報告ありがとうございます!

**Comment by nagayasu-shinya** [comment]
おお！あっという間に修正が！！
ありがとうございます！
