### ISSUE TITLE
casting away a const qualification

### ISSUE THREAD

**Issue by nagayasu-shinya** [yuki-kimoto/SPVM-solo#23]
SPerl_ARRAY_push関数についてです。

SPerl_ARRAY_push関数は引数の型が void* ですがそこにconst char* な文字列リテラルへのポインタを渡しています。const char *型からvoid *型へのキャストになり、const修飾が外れてしまいリードオンリーでなくなってしまいます。

sperl_type.c:46:52: warning: passing 'const char [4]' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        SPerl_ARRAY_push(resolved_type_part_names, "sub");
                                                   ^~~~~

コードをざっとみた限り、渡した文字列リテラルを変更することはないようでした。そうならば、引数の型を void * 出なく const void *にする方が安全かと思います。その場合は、合わせて構造体 struct SPerl_array のメンバ values もconst void **にする必要がありますね。

上記の認識（渡した文字列リテラルは変更しない）でそういなければ、const を外さないように修正してみてプルリクエスト投げます。

よろしくご確認お願い致します。

**Comment by akinomyoga** [comment]
確かに気になる点です。同じファイルの下2つの `SPerl_ARRAY_push` でキャスト `(void*)` を追加したのは私ですが、同じ理由によるものです (`uv.char_value` 及び `part_name` の型を修正した時に追加しました)。

ただ、問題点は `SPerl_ARRAY` はここだけではなくて、他の箇所で、変更可能でなければならない値を格納するのにも使われているということです。従って、最終的には何処かがしわ寄せを受けなくてはなりません。

----
A. 現状だと、変更不能な値を使用するとき

- A1. `SPerl_ARRAY_push` を呼び出すとき、キャスト `(void*)` で明示的に `const` を除く必要が出てきます。

B. 一方で受け取る時に `const` を付加する場合、変更可能な値を使用するとき以下の何れかの箇所で const を外さなければなりません。

- B1. `SPerl_ARRAY_push` 内部で、`array->values[]` に代入する時に `const` を除く、または、
- B2. `SPerl_ARRAY_fetch/pop` 内部で、戻り値を返す時に `const` を除く、または、
- B3. `SPerl_ARRAY_fetch/pop` の呼び出し元で、値を変更したい時に `const` を除く必要があります。

C. 或いは、変更可能な配列とそうでない配列を二重に作るという可能性もありますが、それは管理が面倒です。また、sperl 中で 1つの配列について全ての要素の `const` 性が常に同じになっているのかどうかにもよります (調べていません)。

----

`SPerl_ARRAY` の性質 (値の `const` 性は保持しない) に鑑みて、警告を抑制する方向で行くのであれば B1 が一つの解かと思います。ただ、その場合には `const` に関係する安全性は皆無です。

安全側に倒すとすれば B3 (実際の変更処理を行う可能性があるコードの近くで `const` 外し) になると思います。しかし、~~見たところ殆どの使用ケースは変更したい (もしくは `free(void*)` に渡したい) 場合に相当するので、殆ど毎回 `const` を外さなければなりませんので面倒です。また "fetch/pop の戻り値の `const` は取り敢えず外す" という習慣になってしまうとそれはそれで危ないです。~~ (**訂正**: 調べた所 `T* var = SPerl_ARRAY_fetch(...)` の形式で引数を受け取っても、最終的には値の変更はしていないようですね。`free(void*)` に渡す以外では `SPerl_ARRAY` の要素は sperl 内で全て `const` のようです。

~~そう考えると~~ A1 のように `SPerl_ARRAY_push` 時に明示的に `const` を外させるようにして、同時に使用者側で注意深く取り出した値を変更しないように気をつけてもらうという考え方もあります。

個人的には、そもそもの設計として `SPerl_ARRAY` は**型も消去する**し **`const` 性も消去する**という設計になっているので、安全性を高めようと `const` の取り扱いを詳しくしようとすることには無理があるような気がします。つまり `const` だけを厳密にしたところで、型については依然として厳密ではないので、ここで頑張っても中途半端にしか安全にならないのではないかという意見です。~~という理由で「`SPerl_ARRAY` は型も `cosnt` も消去するものだ」と割り切ってしまうと B1 が綺麗な気がします。~~(**追記**: もし `SPerl_ARRAY` が `const` な値専用の配列ということであれば、B3 の方法 (`free` の時にだけ `const` を外す) で良いですね。)

長文になってしまいすみません。上は勝手に余り考えず書いたものですので、どうぞ忌憚なくご意見・異論・疑問など下さればと思います。

**Comment by nagayasu-shinya** [comment]
SPerl_ARRAY は変更する可能性があるのですね、すみません、そもそもの認識が間違えていました。
「 SPerl_ARRAY は型も消去するし const 性も消去するという設計」というのもわかりました、ジェネリックっぽい感じですね、ありがとうございます。

一番きがかりなのは、実行する環境です。PCならば、えいやっとconst外しでもいいかなあと思います。ただ、組込みのような環境だと、constはほんとうにリードオンリー領域（Flash Memoryとか）に配置されるので、const外しが使えません。組込み機器は非サポートとしちゃうかどうか、ですね。。。

まだ全コードを読めていませんので、ちなみになんですが、文字列リテラルでなくヒープを使うのは、どうでしょうか。イメージはこんな感じ。

char *str_p;
str_p = malloc(strlen("sub") + 1);
(void) strcpy(str_p, "sub");
SPerl_ARRAY_push(resolved_type_part_names, str_p);

もしくはchar配列とか（realloc/free は使わないとして）。

char str[] = "sub";
SPerl_ARRAY_push(resolved_type_part_names, str);

んー、、、変更箇所が多すぎますかね？

**Comment by akinomyoga** [comment]
お返事、ありがとうございます!

> SPerl_ARRAY は変更する可能性があるのですね、すみません、そもそもの認識が間違えていました。

すみません。変更する可能性があるというのは私の勝手な認識でしたので、本来どの認識が正しいのかは分かりません。コードを調べた結果、実際に変更している部分は (`free` 以外に) 見当たりませんでした。`SPerl_ARRAY` が変更をしない配列として設計されたのかどうかは @yuki-kimoto さんに直接お聞きしなければ分かりませんね…。@yuki-kimoto さん、いかがでしょうか。

> ただ、組込みのような環境だと、constはほんとうにリードオンリー領域（Flash Memoryとか）に配置されるので、

なるほど。組込みではまた事情が異なるのですね。

組込みの C では read-only 領域へのポインタの型から const を剥がすだけでエラーになってしまうのでしょうか。"実際にそのポインタを介して書き込みを試行しない限りは大丈夫" などということはありませんかね。というのも、PC (など) の場合でもメモリ領域(ページなど)ごとに read-only などの protect をかけることができますが、ポインタの型から const を剥がすだけでは何も起こらず、実際に書き込みを試行しない限りはエラーになりません。知る限り PC (など) では、ポインタの const キャストは単にコンパイル時に許容する操作を指定する役割しかなくて、(書き込みや読み込みの操作が同じ限り) 実際のコンパイル結果 (機械語) には影響を与えません。

**Comment by nagayasu-shinya** [comment]
ご推察の通り、組み込みでもconstをはずすのはとくに命令語は変化しません。ただ、constをつけるとRAMでなくROMにおかれる場合が多いので、const外して書き込もうとしてもできないです。
ということで、おっしゃるようにconst外すだけで書き込まなければ動作上はだいじょぶかと。

あ。こまかいことで恐縮ですが、組み込み屋は習性としてconst外しはコンパイルエラーになるようにコンパイルオプションをつけることがおおいので、その点だけ注意書きしておけばよさそうですね。

**Comment by akinomyoga** [comment]
> あ。こまかいことで恐縮ですが、組み込み屋は習性としてconst外しはコンパイルエラーになるようにコンパイルオプションをつけることがおおいので、

なるほど。そういうことなのですね。この点が丁度こちらの疑問に対する答えになっていますね。すっきりしました。ありがとうございます!

**Comment by nagayasu-shinya** [comment]
@akinomyoga  さん、こちらこそありがとうございました！やっぱりそれぞれで着眼点が異なるんですね!楽しいですね！

**Comment by akinomyoga** [comment]
そうですね! 変更に関しては、取り敢えずは @yuki-kimoto さんのお考えをお待ちすることにしましょうか。

**Comment by nagayasu-shinya** [comment]
ですね。 @yuki-kimoto さん待ちでｗ

**Comment by yuki-kimoto** [comment]
@nagayasu-shinya さん、constに関する話題を投稿してくださってありがとうございます。

SPerl_ARRAYは、Javaでいうジェネリックのようなもので、「どんなポインタ」でも格納できるようにしている配列になります。格納される値は、変更されうる可能性もあります。

@akinomyoga さんの

>個人的には、そもそもの設計として SPerl_ARRAY は型も消去するし const 性も消去するという設計になっているので、安全性を高めようと const の取り扱いを詳しくしようとすることには無理があるような気がします。

という部分と認識が一致しています。

**Comment by nagayasu-shinya** [comment]
なるほど。C言語でなんでも受け取れるようにするにはvoid*しかないですもんね。。。なるほど、諒解しました。

const を避けるための

char *str_p;
str_p = malloc(strlen("sub") + 1);
(void) strcpy(str_p, "sub");
SPerl_ARRAY_push(resolved_type_part_names, str_p);

の案は、ＮGなんですよね。。。むむー。
もし、グッドでナイスなアイデア思いついたら、また相談させてください。
ありがとうございました

**Comment by akinomyoga** [comment]
@yuki-kimoto さん。お返事、ありがとうございます。

そういうことでしたら、先のコメントの B1 の方法 (`SPerl_ARRAY_push` は `const void*` で受け取って、中で `(void*)` に明示キャストする) が自然に思われます。

(**追記**) Note: `strstr` や `strpbrk` の類と同じ発想ということになります

**Comment by nagayasu-shinya** [comment]
そうですね、それが良いかと思うです！
あえてやっている、とコメントがあればさらに親切ですね。

**Comment by akinomyoga** [comment]
@nagayasu-shinya さんの `malloc & strcpy` には不自然な overhead がありますから避けたいところです。

個人的には、使う側でちゃんと "本来は書き込み禁止" ということを承知して取り扱うのでしたら、途中で `void*` になったりするのは普通に受け入れられる気がします。それを迂回する為に `malloc & strcpy` するのは、大げさというか本質を逸したトリックというような印象を受けます。

**Comment by akinomyoga** [comment]
> あえてやっている、とコメントがあればさらに親切ですね。

そうですね! それがよいです! 変更お願いできますか? to @nagayasu-shinya さん

**Comment by nagayasu-shinya** [comment]
`個人的には、使う側でちゃんと "本来は書き込み禁止" ということを承知して取り扱うのでしたら、途中で void* になったりするのは普通に受け入れられる気がします。それを迂回する為に malloc & strcpy するのは、大げさというか本質を逸したトリックというような印象を受けます。`
自分で言っておきながら私も、オーバーヘッドに関しては全くの同意です。ＰＣならなおさらもさいですね。ここら辺が、バランスのとりどころ。
ということで、コメントが妥当だと思います！

**Comment by akinomyoga** [comment]
そうですね! 組込みの色々の事情だったり、あるいは、規約で縛られている中で規約の穴を突いたりという時には、そういう選択肢を採ることもあるのだろうなあと、こちらも色々考えました。

**Comment by yuki-kimoto** [comment]
mallocはオーバーヘッドがあるので、避けたいです。

B1案で、進めてみるのはいかがでしょう。

**Comment by nagayasu-shinya** [comment]
👍 賛成です！

**Comment by nagayasu-shinya** [comment]
B2. SPerl_ARRAY_fetch/pop 内部で、戻り値を返す時に const を除く
で実装してみますねー。コメントも入れてみますー。
週末にはプルリします！

**Comment by yuki-kimoto** [comment]
お願いしまーす!
