### ISSUE TITLE
Discussion on refinement/simplification of Makefile

### ISSUE THREAD

**Issue by akinomyoga** [yuki-kimoto/SPVM-solo#5]
以下について議論させて頂きたくここに Issue を立てます

- Makefile 内部に説明のコメント
- オブジェクトファイル生成場所
- テスト用バイナリの生成場所・テストの実行方法
- Makefile 簡素化の方針

**Comment by akinomyoga** [comment]
取り敢えず明日、Makefile にコメントを付加したものを作ることにします。
その他の項目についても何かありましたらこちらにお願い致します。

**Comment by yuki-kimoto** [comment]
@akinomyoga 

こちらからの続きで。

https://github.com/yuki-kimoto/static-perl/pull/3

作ってもらったmake便利ですね。ありがとうございます。

最終的な目標としては、Perlから実行できるようにしたいんです。

つまりPerlのCバインディング(これをXSといいます。)として、ダイナミックリンクライブラリ(.so)を作成して、呼び出すという形です。

1. Makefile.PLを実行することによって、Makefileを生成する。(Makefile.PLはExtUtils::MakeMakerというモジュールを使って書きます。http://search.cpan.org/~bingos/ExtUtils-MakeMaker-7.24/lib/ExtUtils/MakeMaker.pm)

サンプル(https://github.com/yuki-kimoto/Rstats/blob/master/Makefile.PL)

2. Makefileを実行すると、static-perlのダイナミックリンクライブラリが出来上がる。

3. これをPerlのCバインディング(XS)から呼び出す

という流れです。

    perl Makefile.PL
    make
    make test
    make install

現在は、static-perlは単体で実行できる形で作っていますので、気にせずにMakefileを作成していただけたらと思います。(後で、移植という形で、大丈夫なはずなので)

**Comment by akinomyoga** [comment]
すみません時間が開いてしまいました (AdC の記事 (遅刻) を書いていました)。

Makefile の分かりにくいところに説明を追加したものを作ろうと考えたのですが、その前にやはり相談して残す所変更する所などを決めてからにした方が良いと感じましたので、先に議論させて下さい。

ところで Issue の上でコードを参照することってできるのでしたっけ (Pull request ではできますけれど…)?

**追記**: 単に tree の id を貼るだけでは駄目のようですね。コード上にコメントを書き込む形で議論できたら良いなと思ったのですが良い方法はありますか (本当はそれをしたくて add-Makefile の Pull request で相談したいと書いたのですけれど、英語でうまくニュアンスが伝えられずそのまま Merge されてしまいました)。

**Comment by yuki-kimoto** [comment]
>ところで Issue の上でコードを参照することってできるのでしたっけ (Pull request ではできますけれど…)?

うーん、できるかどうか、わからないです。

>単に tree の id を貼るだけでは駄目のようですね。コード上にコメントを書き込む形で議論できたら良いなと思ったのですが良い方法はありますか

コントリビューターに追加しますので、議論用のブランチを一つ作成して、そこで、互いに修正するというのはいかがですか?

**Comment by akinomyoga** [comment]
> コントリビューターに追加しますので、議論用のブランチを一つ作成して、そこで、互いに修正するというのはいかがですか?

ありがとうございます。それで問題ありません。

**Comment by yuki-kimoto** [comment]
コントリビューターではなくって、コラボレーターでした。

コラボレーターに追加しましたので、sshで、このリポジトリをpush,pullできます。
Makeファイル用のブランチを、作ってみてください。

**Comment by akinomyoga** [comment]
ありがとうございます。取り敢えず `spike-makefile` branch で以下にコメントを加えました。

SUFFIXES と sperl_yacc.c に関し: @7ebbb4be503325a260ee23a8e2ca5de4a168df14

よろしくおねがいいたします。
(**Update**: refs PR #9 merged)

**Comment by akinomyoga** [comment]
コンパイラの警告の表示と uint8 文字列に関し: @7ae209b7e92565a21212e9a4de8f7fcc84205493
(**Update**: refs PR #6, #7 merged, Comments on @2ebe9eac015ac342f8f6c5c8f5322c2ac80f2dc5)

**Comment by akinomyoga** [comment]
オブジェクトファイルの出力先に関し: @5ae409bc34bcbecb6447e6dd47623f20b12f2501
(**Update**: refs PR #9 merged)

**Comment by yuki-kimoto** [comment]
warningsがでている部分は、少しづつなおしていきたいと思います。

**Comment by yuki-kimoto** [comment]
unused parameterの警告ってなんとかならないものですかね?

オブジェクト指向プログラミングなので、第一引数には、常に、親オブジェクトがわたるもので。

**Comment by akinomyoga** [comment]
それについて丁度疑問に思われると考えて以下にコメントしておいたのですが、ご覧になっていただけましたか。

https://github.com/yuki-kimoto/static-perl/commit/7ae209b7e92565a21212e9a4de8f7fcc84205493#commitcomment-20322756

説明がわかりにくければこちらで編集してまた PR 出します。
よろしくおねがいいたします。

**Comment by akinomyoga** [comment]
あけましておめでとうございます。
テスト用バイナリの生成場所について: @d8db274b9dba20958175cdb3c54a6fda667478a0
にコメントを入れました。ご確認下さい。
(**Update**: refs PR #9 merged)

**Comment by yuki-kimoto** [comment]
あけましておめでとうございます。

**Comment by akinomyoga** [comment]
@d8db274b9dba20958175cdb3c54a6fda667478a0 に対するお答えありがとうございます。取り敢えずこの時点までで Makefile に対して決定したことについて PR を出したいと考えているのですがいかがでしょうか。

- 変更には `sperl_yacc.{c,h}` → `sperl_yacc_util.{c,h}` などのファイル名変更が含まれているので、別 branch で `sperl_yacc.{c,h}` を編集している場合は注意が必要です。
- また `sperl_descripter.{c,h}` のスペルミスが気になるので `sperl_descriptor.{c,h}` への改名も含めましょうか。

**Comment by yuki-kimoto** [comment]
一つ目ですが、masterブランチが最新版なので、だいじょうぶです。

二つ目ですが、スペルミスの修正をお願いいたいします。

**Comment by akinomyoga** [comment]
承知です。今 Makefile 及びファイル名の更新を行っています。

**Comment by akinomyoga** [comment]
現状の Makefile について説明しておきます。

- 既にお気づきかと思いますが、(1) 先ず `*.c` からライブラリ `libsperl.a` を生成し、(2) `main/sperl_main.c`, `t/sperl_t_*.c` をコンパイルする時は `libsperl.a` にリンクするという形にしています。

また簡素化に関して。"簡素" には考え方が二つあって、

- Make (GNU Make) の機能を惜しみなく使って短く書く (つまり、`sper_t_%` (パターンルール) や `$(wildcard *.c)` (文字列処理の関数) を使ってルールを一括で指定する)。
- もしくは簡単な機能だけを使って、パターンルールや `$(wildcard *.c)` などに対応する部分は全部手動でべた書き (羅列) する

というものです。前者は管理が楽ですが、(多少ソースをいじろうとする程度の) ユーザに知識を要求します。後者は、記述・管理が面倒ですが、(GNU make 以外の) 様々の make でも動きます。またぱっとみてどんなルールが実際に生成されているかが分かります。

現状では前者の方です。実際の配布時には恐らく Makefile.PL によって生成される Makefile を使用するということ (?) のようですので、"開発用の Makefile" として GNU Make に限定するという立場でこのままで良いのではないかと考えております。また @yuki-kimoto さんもこの Makefile の内容をよく理解されているように感じたのもその理由です。

べた書きに直した方が良いという意見がありましたら修正します。よろしくおねがいいたします。
また Makefile 中にコメントによる解説があったほうが良いということでしたらその追加もします。
現状で問題がなければ close ということで構いません。

**Comment by yuki-kimoto** [comment]
>現状では前者の方です。実際の配布時には恐らく Makefile.PL によって生成される Makefile を使用するということ (?) のようですので、"開発用の Makefile" として GNU Make に限定するという立場でこのままで良いのではないかと考えております。

「GNU make」で実行できれば大丈夫なので、現状でOKです。

ありがとうございます。クローズします。

**Comment by akinomyoga** [comment]
ありがとうございます
